title: NNRL's Homepage
page-top-title: NNRL
top-section-bg-text: Neuroscience and Neuroengineering Laboratory (NNRL)
home-subtitle: Neuroscience and Neuroengineering Laboratory (NNRL)
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
